### ISSUE TITLE
Question rather than issue

### ISSUE THREAD

**Issue by 80kk** [constantinjoly/512-Kirby-theme#1]
Hi Constantin,
Could you please tell me how/where to modify the code to change the amount of blank space between Headline, Introduction and Sections if you decide to leave Headline field blank?
regards,

**Comment by constantinjoly** [comment]
Hi,
If you mean pages like Projects, Services etc... the theme allows you to omit the Headline field, but it will be replaced by default with the default title of the page. To reduce vertical spacing of the header if the introduction field is empty, you will need to reduce the margin on the _Header class .intro_ witch is actualy set to:

`
.intro {
    width: 100%;
    max-width: 48rem;
    margin: 9rem auto;
}
`

I hope it will help you, feel free to give more details ;-)

**Comment by 80kk** [comment]
> Hi,
> If you mean pages like Projects, Services etc... the theme allows you to omit the Headline field, but it will be replaced by default with the default title of the page. To reduce vertical spacing of the header if the introduction field is empty, you will need to reduce the margin on the _Header class .intro_ witch is actualy set to:
> 
> `.intro { width: 100%; max-width: 48rem; margin: 9rem auto; }`
> 
> I hope it will help you, feel free to give more details ;-)

So I'm doing something wrong then. I've changed it to:
`.intro { width: 100%; max-width: 48rem; margin: 9rem 100px; }`
I've also tried to change width and max-width values but with no result and this is what I want to change:
https://ibb.co/KD3wH3Y

**Comment by constantinjoly** [comment]
Hi,
Yes, here 

`margin: 9rem 100px;` 

means: 

margin-top:9rem
margin-bottom:9rem
margin-left and margin-right: 100px

If you want to change vertical margin use for exemple: 

`margin: 2rem auto;` or
`margin: 2rem auto 1rem auto`

Auto is used in left and right to center element in its container

**Comment by 80kk** [comment]
So I'm doing something wrong as this doesn't make any difference. Please take a look on my css file: http://codepad.org/tD8dfIOq (line 481)

**Comment by constantinjoly** [comment]
I just tried you code and it works fine. Issue is somewhere else. Please send me a message with a link to your website in Kirby forum or  by email (check my website) if you want me to help. I close the issue here.
Thank you.
